version: '3'

services:
  db:
    image: mariadb:$mariaTag
    restart: unless-stopped
    container_name: nxtclouddb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - ${cloudDir}/datadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=Password1!2@
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud


  app:
    image: nextcloud-js
    container_name: nxtcloud
    restart: unless-stopped
    ports:
      - 8081:443
      - 8080:80
    links:
      - db
    volumes:
      - ${cloudDir}/data:/var/www/html
    environment:
      - MYSQL_PASSWORD=Password1!2@
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
